### ISSUE TITLE
Documentation: performance

### ISSUE THREAD

**Issue by kown7** [SanDisk-Open-Source/pyvcd#9]
Using the following yields around 30% better performance on my systems.

```python
fp = io.StringIO()
with VCDWriter(fp, timescale=(10, 'ns'), date='today') as writer:
    counter_var = writer.register_var('a.b.c', 'counter', 'integer',
                                      size=8)
    for i in range(1000, 30000000, 300):
        for timestamp, value in enumerate(range(10, 200, 2)):
            writer.change(counter_var, i + timestamp, value)
with open('test3.vcd', 'w+') as fd:
    fp.seek(0)
    shutil.copyfileobj(fp, fd)
fp.close()
```

**Comment by jpgrayson** [comment]
Hi @kown7. Thanks for this observation.

I was able to get a similar result when comparing to using a regular buffered file io (i.e. `open('test3.vcd', 'w')`.

My strong suspicion is that the performance difference comes from more efficient encoding from Python's internal representation to ascii/utf-8 when encoding the entire StringIO buffer in one-shot versus encoding each time more data is written in the buffered file io case.

A potential enhancement to pyvcd would be to be more explicitly ascii/bytes oriented such that encoding costs can be minimized. Also, pyvcd is currently exposed to outputting non-ascii characters since it uses the encoding of whatever file object is passed-in and will accept strings containing non-ascii characters for timescale, date, scope, var name, etc.

**Comment by kown7** [comment]
Hi @jpgrayson 

Apologies for not posting the entire performance measuring script. I haven't looked into the code, but I stumbled over the ```print``` print statements while trying the above improvements before.

Here's a hypothesis: it's the ```print```statements `a`. Run this on your own to verify:

```python
timeit.timeit('print(\"Hello world\", file=fd)', setup='import sys; fd=open(\"test2.vcd\", mode=\"w\")', number=100_000_00)
timeit.timeit('fd.write(\"Hello world\\n\")', setup='import sys; fd=open(\"test.vcd\", mode=\"w\")', number=100_000_00)
```

Print comes out about a factor >4 slower.

**Comment by kown7** [comment]
PS: using `io.StringIO` and `write()` doesn't make a difference compared to using `write()` directly on a file.

**Comment by jpgrayson** [comment]
Verified that using `write()` instead of `print()` nets ~20% performance improvement in my environment which is on par with the `StringIO` method above.

I will push a change that switches pyvcd to use `write()` and cut a release.

This is a really nice improvement. Thanks for your help identifying the issue!
